# Generated by Django 4.1.5 on 2023-01-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('int_from', models.IntegerField(blank=True, null=True)),
                ('int_to', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Schema Column',
                'verbose_name_plural': 'Schema Columns',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('column_sep', models.CharField(max_length=1)),
                ('string_char', models.CharField(max_length=1)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.ManyToManyField(blank=True, to='schemas.schemacolumn')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'ordering': ('-created_at',),
            },
        ),
    ]
