# Generated by Django 4.1.5 on 2023-01-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0004_schema_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schemacolumn",
            options={
                "ordering": ("-order",),
                "verbose_name": "Schema Column",
                "verbose_name_plural": "Schema Columns",
            },
        ),
        migrations.RenameField(
            model_name="schemacolumn",
            old_name="type",
            new_name="column_type",
        ),
    ]
