# Generated by Django 4.1.5 on 2023-01-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0005_alter_schemacolumn_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schemacolumn",
            options={
                "ordering": ("order",),
                "verbose_name": "Schema Column",
                "verbose_name_plural": "Schema Columns",
            },
        ),
    ]
